platform :ios, '10.0'

target 'Trading Insights' do
  use_frameworks!

  pod 'AKSideMenu', '1.3.1'
  pod 'Alamofire', '4.2.0'
  pod 'AlamofireObjectMapper', '4.0.1'
  pod 'Dollar', '6.1.0'
  pod 'Material', '2.4.0'
  pod 'PromiseKit', '4.1.0'
  pod 'RealmSwift', '2.1.1'
  pod 'Reveal-SDK', '4', :configurations => ['Debug']
  pod 'SnapKit', '3.0.2'
  pod 'SwiftyTimer', '2.0.0'
  pod 'SwiftyUserDefaults', '3.0.0'

  target 'Trading InsightsTests' do
    inherit! :search_paths
  end

  target 'Trading InsightsUITests' do
    inherit! :search_paths
  end

end
