platform :ios, '9.0'
use_frameworks!

target 'Music Discovery' do
  pod 'Alamofire', '4.0.1'
  pod 'AlamofireNetworkActivityIndicator', '2.0.1'
  pod 'AlamofireObjectMapper', '4.0.0'
  pod 'AsyncDisplayKit', '1.9.91'
  pod 'Dollar', '6.0.0'
  pod 'FileKit', '4.0.0'
  pod 'Material', '2.2.1'
  pod 'NBMaterialDialogIOS', :git => "https://github.com/Gerst20051/NBMaterialDialogIOS.git", :branch => "swift3" # '1.0.0'
  pod 'NMPopUpViewSwift', :git => 'https://github.com/Gerst20051/NMPopUpView.git', :branch => 'swift3' # '5.0.0'
  pod 'NVActivityIndicatorView', '3.0'
  pod 'PromiseKit', '4.0.4'
  pod 'RealmSwift', '2.0.2'
  pod 'Reveal-SDK', '2.0.0', :configurations => ['Debug']
  pod 'SnapKit', '3.0.2'
  pod 'SwiftyTimer', '2.0.0'
  pod 'SwiftyUserDefaults', '3.0.0'
  pod 'XCDYouTubeKit', '2.5.3'
end
