platform :ios, '9.0'
use_frameworks!

target 'Music Discovery' do
  pod 'Alamofire', '3.4.1'
  pod 'AlamofireNetworkActivityIndicator', '1.0.1'
  pod 'AlamofireObjectMapper', '3.0.0'
  pod 'Dollar', '5.1.0'
  pod 'FileKit', '2.0.0'
  pod 'Material', '1.42.6'
  pod 'NBMaterialDialogIOS', '0.2.2'
  pod 'NMPopUpViewSwift', '3.0.1'
  pod 'NVActivityIndicatorView', '2.8'
  pod 'PromiseKit/CorePromise', '3.2.0'
  pod 'RealmSwift', '1.0.1'
  pod 'SnapKit', '0.21.0'
  pod 'SwiftyUserDefaults', '2.2.0'
  pod 'XCDYouTubeKit', '2.5.3'
end
