platform :ios, '9.0'

target 'Stock Market Discovery' do
  use_frameworks!

  pod 'Alamofire', '4.1.0'
  pod 'AlamofireObjectMapper', '4.0.0'
  pod 'Charts', '3.0.0'
  pod 'CSV.swift', '1.1.1'
  pod 'Dollar', '6.1.0'
  pod 'Material', '2.3.10'
  pod 'PromiseKit', '4.0.4'
  pod 'RealmSwift', '2.0.4'
  pod 'Reveal-SDK', '4', :configurations => ['Debug']
  pod 'SnapKit', '3.0.2'
  pod 'SwiftCharts', :git => 'https://github.com/i-schuetz/SwiftCharts.git'
  pod 'SwiftyTimer', '2.0.0'
  pod 'SwiftyUserDefaults', '3.0.0'

  target 'Stock Market DiscoveryTests' do
    inherit! :search_paths
  end

  target 'Stock Market DiscoveryUITests' do
    inherit! :search_paths
  end

end
