# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Stock Market Discovery' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Stock Market Discovery

  target 'Stock Market DiscoveryTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Stock Market DiscoveryUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
