platform :osx, '10.10'

target 'Gitlab Client' do
  use_frameworks!

  pod 'Alamofire', :git => 'https://github.com/Alamofire/Alamofire.git', :branch => 'swift3' # '3.4.1'
  pod 'Dollar', :git => 'https://github.com/ankurp/Dollar.git', :branch => 'swift-3' # '5.1.0'
  pod 'Material', :git => 'https://github.com/CosmicMind/Material.git', :branch => 'development' # '2.0.0'
  pod 'PromiseKit', :git => 'https://github.com/mxcl/PromiseKit.git', :branch => 'swift-3.0' # '4.0.0'
  pod 'SnapKit', :git => 'https://github.com/SnapKit/SnapKit', :branch => 'feature/0.40.0' # '0.40.0.beta2'
  pod 'SwiftyUserDefaults', git: 'https://github.com/radex/SwiftyUserDefaults.git', branch: 'swift3' # '2.2.0'

  target 'Gitlab ClientTests' do
    inherit! :search_paths
  end

  target 'Gitlab ClientUITests' do
    inherit! :search_paths
  end
end
