platform :osx, '10.10'

target 'Gitlab Client' do
  use_frameworks!

  pod 'Material', :git => 'https://github.com/CosmicMind/Material.git', :branch => 'development'

  target 'Gitlab ClientTests' do
    inherit! :search_paths
  end

  target 'Gitlab ClientUITests' do
    inherit! :search_paths
  end

end
