# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'Gitlab Client' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Gitlab Client

  target 'Gitlab ClientTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Gitlab ClientUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
