platform :ios, '9.0'

target 'PodBuddy' do
  use_frameworks!

  pod 'Alamofire', '4.4.0'
  pod 'AlamofireObjectMapper', '4.1.0'
  pod 'Dollar', '6.2.0'
  pod 'Material', '2.6.3'
  pod 'PromiseKit', '4.1.7'
  pod 'RateLimit', '2.1.1'
  pod 'RealmSwift', '2.5.1'
  pod 'Reveal-SDK', '8', :configurations => ['Debug']
  pod 'SnapKit', '3.2.0'
  pod 'SwiftSpinner', '1.2.1'
  pod 'SwiftyTimer', '2.0.0'
  pod 'SwiftyUserDefaults', '3.0.0'

  target 'PodBuddyTests' do
    inherit! :search_paths
  end

  target 'PodBuddyUITests' do
    inherit! :search_paths
  end

end
