devices(["iPhone 6", "iPhone 6 Plus", "iPhone 5", "iPhone 4s", "iPad Retina", "iPad Pro"])

languages(["en-US"])

scheme "Music Discovery UITests"

clean true
erase_simulator true
number_of_retries 0
reinstall_app true
stop_after_first_error true

workspace "./Music Discovery.xcworkspace"
