platform :ios, '9.0'

target 'CalendarNotes' do
  use_frameworks!

  pod 'Alamofire', '4.7.2'
  pod 'AlamofireObjectMapper', '5.0.0'
  pod 'Dollar', '7.1.0'
  pod 'Material', '2.15.0'
  pod 'PromiseKit', '6.2.7'
  pod 'RealmSwift', '3.5.0'
  pod 'Reveal-SDK', '14', :configurations => ['Debug']
  pod 'SnapKit', '4.0.0'
  pod 'SwiftyTimer', '2.0.0'
  pod 'SwiftyUserDefaults', '4.0.0-alpha.1'

  target 'CalendarNotesTests' do
    inherit! :search_paths
  end

  target 'CalendarNotesUITests' do
    inherit! :search_paths
  end

end
